spring:
  application:
    name: service-erueka-register

server:
  port: 8802
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 15
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/, http://127.0.0.1:8801/eureka/
      #http://${eureka.instance.hostname}:${server.port}/eureka/
