eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8801/eureka/
      #也可以两个都注册，一个够了会相互注册，如 http://127.0.0.1:8801/eureka/, http://127.0.0.1:8802/eureka/
server:
  port: 8804  #服务端口号
spring:
  application:
    name: service-provider #服务名称--调用的时候根据名称来调用该服务的方法
